* About

[[https://github.com/jakub-stastny/blog/actions/workflows/test.yml][https://github.com/jakub-stastny/blog/actions/workflows/test.yml/badge.svg]]

My blog written in Elm and Elm UI. My raw blog posts are available [[https://github.com/jakub-stastny/data.blog][here]].

** Literate programming

In case you're wondering where are all the Elm files, you have to tangle Elm blocks from [[https://orgmode.org][Org mode]] files in =src= into actual Elm files using Org mode in Emacs.

This allows not only better documentation, since Org mode files are structured text, unlike comments, but also it allows us to have code and related tests at the same Org file, so we can keep related things in one place. These get tangled into separate Elm files of course.

* Setup

See [[./.env/README.org][.env/README.org]] for literate DevOps instructions on setting the project.

* Pending matters
** TODO Elm code compilation on GH CI

Move contents of =bin/compile.el= into the GH action file.

** TODO Respect header tangle property

See why the header tangle property is not being respected.
